# Generated by Django 5.1 on 2024-08-18 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_pessoa_apelido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='idade',
        ),
    ]
