# Generated by Django 5.1 on 2024-08-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='nota_media',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
