# Generated by Django 5.1 on 2024-08-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='logo_path',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/campeonato/'),
        ),
    ]
