# Generated by Django 5.1 on 2024-08-31 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0002_campeonato_nota_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campeonato',
            name='logo_path',
            field=models.ImageField(blank=True, null=True, upload_to='media/campeonato/'),
        ),
    ]
