# Generated by Django 5.1 on 2024-08-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0004_alter_campeonato_logo_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campeonato',
            name='logo_path',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
