# Generated by Django 5.1 on 2024-08-27 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('jogador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('estrelas', models.IntegerField()),
                ('comentario', models.TextField()),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogador.jogador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pessoa')),
            ],
        ),
    ]
