# Generated by Django 5.1 on 2024-08-28 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('jogador', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogador.jogador')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pessoa')),
            ],
        ),
    ]
