# Generated by Django 5.1 on 2024-08-27 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('avaliacao', '0001_initial'),
        ('jogador', '0002_jogador_nota_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoJogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogador.jogador')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pessoa')),
            ],
        ),
        migrations.DeleteModel(
            name='Avaliacao',
        ),
    ]
