# Generated by Django 5.1 on 2024-08-30 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('avaliacao', '0001_initial'),
        ('campeonato', '0002_campeonato_nota_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoCampeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonato.campeonato')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pessoa')),
            ],
        ),
    ]
