# Generated by Django 5.1 on 2024-08-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Federacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=3)),
                ('localidade', models.CharField(max_length=100)),
                ('logo_path', models.CharField(max_length=250)),
                ('presidente', models.CharField(max_length=100)),
                ('fundacao', models.DateField()),
                ('afiliada', models.ManyToManyField(to='federacao.federacao')),
            ],
        ),
    ]
