# Generated by Django 5.1 on 2024-08-28 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Federacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10)),
                ('localidade', models.CharField(max_length=100)),
                ('logo_path', models.CharField(max_length=250)),
                ('presidente', models.CharField(max_length=100)),
                ('fundacao', models.DateField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('afiliada', models.ManyToManyField(blank=True, related_name='afiliacoes', through='federacao.Afiliacoes', to='federacao.federacao')),
            ],
        ),
        migrations.AddField(
            model_name='afiliacoes',
            name='federacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='federacao', to='federacao.federacao'),
        ),
        migrations.AddField(
            model_name='afiliacoes',
            name='federacao_afiliada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='federacao_afiliada', to='federacao.federacao'),
        ),
    ]
