# Generated by Django 5.1 on 2024-08-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federacao',
            name='afiliada',
            field=models.ManyToManyField(blank=True, to='federacao.federacao'),
        ),
    ]
