# Generated by Django 5.1 on 2024-09-04 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('federacao', '0002_alter_federacao_logo_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='federacao',
            name='comentarios',
        ),
        migrations.DeleteModel(
            name='ComentariosFederacao',
        ),
    ]
