# Generated by Django 5.1 on 2024-08-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_jogador', models.CharField(max_length=100)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('descricao', models.TextField(default='Não há descrição disponível para esse jogador')),
                ('altura', models.FloatField()),
                ('melhor_pe', models.CharField(choices=[('Esquerdo', 'Esquerdo'), ('Direito', 'Direito'), ('Ambidestro', 'Ambidestro')], max_length=100)),
                ('foto_path', models.CharField(max_length=250)),
                ('fotoCapa_path', models.CharField(max_length=250)),
                ('nota_media', models.FloatField(default=0.0, editable=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
