# Generated by Django 5.1 on 2024-08-17 19:50

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_pessoa_rename_nome_usuario_apelido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.pessoa')),
                ('nacionalidade', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('altura', models.FloatField()),
                ('melhor_pe', models.CharField(choices=[('Esquerdo', 'Esquerdo'), ('Direito', 'Direito'), ('Ambidestro', 'Ambidestro')], max_length=100)),
                ('foto_path', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('accounts.pessoa',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
