# Generated by Django 5.1 on 2024-08-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='nota_media',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
