# Generated by Django 5.1 on 2024-08-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jogador',
            options={},
        ),
        migrations.AlterModelManagers(
            name='jogador',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='pessoa_ptr',
        ),
        migrations.AddField(
            model_name='jogador',
            name='fotoCapa_path',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jogador',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jogador',
            name='nome_jogador',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
