# Generated by Django 5.1 on 2024-08-28 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0002_remove_clube_jogadores'),
        ('jogador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='clube',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clube.clube'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='posicao',
            field=models.CharField(choices=[('Goleiro', 'Goleiro'), ('Zagueiro', 'Zagueiro'), ('Lateral Esquerdo', 'Lateral Esquerdo'), ('Lateral Direito', 'Lateral Direito'), ('Volante', 'Volante'), ('Meio Campo', 'Meio Campo'), ('Meia atacante', 'Meia atacante'), ('Ponta esquerda', 'Ponta esquerda'), ('Ponta direita', 'Ponta direita'), ('Centroavante', 'Centroavante'), ('Atacante', 'Atacante')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jogador',
            name='descricao',
            field=models.TextField(),
        ),
    ]
