# Generated by Django 5.1 on 2024-08-28 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('jogador', '0002_jogador_clube_jogador_posicao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_jogador', to='jogador.jogador')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_pessoa', to='accounts.pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='jogador',
            name='comentarios',
            field=models.ManyToManyField(blank=True, related_name='jogador_comentarios', through='jogador.Comentarios', to='accounts.pessoa'),
        ),
    ]
