# Generated by Django 5.1 on 2024-09-04 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0002_alter_jogador_fotocapa_path_alter_jogador_foto_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='comentarios',
        ),
        migrations.DeleteModel(
            name='ComentariosJogador',
        ),
    ]
