# Generated by Django 5.1 on 2024-08-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0002_alter_jogador_options_alter_jogador_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='comentarios',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
