# Generated by Django 5.1 on 2024-08-29 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0002_jogador_nota_media'),
        ('jogador', '0003_comentarios_jogador_comentarios'),
    ]

    operations = [
    ]
