# Generated by Django 5.1 on 2024-08-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0003_jogador_comentarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='avaliacao',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='comentarios',
        ),
        migrations.AlterField(
            model_name='jogador',
            name='descricao',
            field=models.TextField(default='Não há descrição disponível para esse jogador'),
        ),
    ]
