# Generated by Django 5.1 on 2024-08-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0004_merge_20240829_0948'),
        ('jogador', '0004_merge_20240829_0950'),
    ]

    operations = [
    ]
