# Generated by Django 5.1 on 2024-08-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogador', '0005_merge_20240829_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='fotoCapa_path',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/jogador/'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='foto_path',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/jogador/'),
        ),
    ]
