# Generated by Django 5.1 on 2024-08-27 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('jogador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=3)),
                ('pais', models.CharField(max_length=100)),
                ('logo_path', models.CharField(max_length=250)),
                ('estadio', models.CharField(max_length=250)),
                ('fundacao', models.DateField()),
                ('jogadores', models.ManyToManyField(to='jogador.jogador')),
                ('presidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubes_presididos', to='accounts.pessoa')),
                ('treinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubes_treinados', to='accounts.pessoa')),
            ],
        ),
    ]
