# Generated by Django 5.1 on 2024-08-28 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('federacao', '__first__'),
        ('jogador', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=3)),
                ('pais', models.CharField(max_length=100)),
                ('logo_path', models.CharField(max_length=250)),
                ('treinador', models.CharField(max_length=100)),
                ('presidente', models.CharField(max_length=100)),
                ('estadio', models.CharField(max_length=250)),
                ('fundacao', models.DateField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.pessoa')),
                ('federacao', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='federacao.federacao')),
                ('jogadores', models.ManyToManyField(to='jogador.jogador')),
            ],
        ),
    ]
