# Generated by Django 5.1 on 2024-08-29 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('federacao', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=5)),
                ('pais', models.CharField(max_length=100)),
                ('logo_path', models.ImageField(blank=True, null=True, upload_to='imagens/clube/')),
                ('treinador', models.CharField(blank=True, max_length=100, null=True)),
                ('presidente', models.CharField(blank=True, max_length=100, null=True)),
                ('estadio', models.CharField(blank=True, max_length=250, null=True)),
                ('fundacao', models.DateField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('nota_media', models.FloatField(default=0.0, editable=False)),
                ('criado_por', models.ForeignKey(auto_created=True, blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.pessoa')),
                ('federacoes', models.ManyToManyField(blank=True, to='federacao.federacao')),
            ],
        ),
        migrations.CreateModel(
            name='ComentariosClube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_clube', to='clube.clube')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_pessoa_clube', to='accounts.pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='clube',
            name='comentarios',
            field=models.ManyToManyField(blank=True, related_name='clube_comentarios', through='clube.ComentariosClube', to='accounts.pessoa'),
        ),
    ]
