# Generated by Django 5.1 on 2024-08-28 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clube',
            name='jogadores',
        ),
    ]
