# Generated by Django 5.1 on 2024-08-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clube',
            name='presidente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clube',
            name='treinador',
            field=models.CharField(max_length=100),
        ),
    ]
