# Generated by Django 5.1 on 2024-08-27 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0002_alter_clube_presidente_alter_clube_treinador'),
        ('federacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='federacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='federacao.federacao'),
        ),
    ]
