# Generated by Django 5.1 on 2024-09-04 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0002_alter_clube_logo_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clube',
            name='comentarios',
        ),
        migrations.DeleteModel(
            name='ComentariosClube',
        ),
    ]
