# Generated by Django 5.1 on 2024-08-27 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_pessoa_idade'),
        ('clube', '0003_clube_federacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='criado_por',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.pessoa'),
        ),
    ]
