# Generated by Django 5.1 on 2024-08-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0003_remove_clube_federacao_clube_federacoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clube',
            name='logo_path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='clube',
            name='presidente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clube',
            name='treinador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
