# Generated by Django 5.1 on 2024-08-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0005_alter_clube_estadio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clube',
            name='fundacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
